version: "3.0"

services:
  product-api:
    build:
      context: .
      dockerfile: ProductAPI/Dockerfile
    image: product-api:latest
    container_name: product-api
    hostname: product-api
    depends_on:
      - mysql
      - redis
    ports:
      - 5000:80
  mysql:
    image: mysql
    container_name: mysql
    hostname: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
  redis:
    image: redis
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
networks:
  default:
      name: innoloft